# Resolution
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Display to start the window in
DISPLAY = 0

#  Hitboxes and sizes
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds!
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5

# Player
PLAYER_SHOT_COOLDOWN = 0.3 # seconds!
PLAYER_RADIUS = 20 # hitbox size
PLAYER_SHOT_SPEED = 500 # velocity
PLAYER_SPEED = 200 # velocity
PLAYER_TURN_SPEED = 300 # velocity
