# Resolution
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#  Hitboxes
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5

# Player
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
